/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.radar;

/**
 *
 * @author darlan
 */
public class Radar extends javax.swing.JFrame {

    /**
     * Creates new form Radar
     */
    public Radar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabAvioes = new javax.swing.JTabbedPane();
        jPnRadar = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListRelatorio = new javax.swing.JList<>();
        jLblRelatorio = new javax.swing.JLabel();
        jPnAvioes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbAvioes = new javax.swing.JTable();
        jPnOperacoesAvioes = new javax.swing.JPanel();
        jTabOperacoesAvioes = new javax.swing.JTabbedPane();
        jPnEntradaDados = new javax.swing.JPanel();
        jPnDadosAviao = new javax.swing.JPanel();
        jLblX = new javax.swing.JLabel();
        jTxtX = new javax.swing.JTextField();
        jLblY = new javax.swing.JLabel();
        jTxtY = new javax.swing.JTextField();
        jLblRaio = new javax.swing.JLabel();
        jTxtRaio = new javax.swing.JTextField();
        jLblAngulo = new javax.swing.JLabel();
        jTxtAngulo = new javax.swing.JTextField();
        jLblVelocidade = new javax.swing.JLabel();
        jTxtVelocidade = new javax.swing.JTextField();
        jLblAngulo1 = new javax.swing.JLabel();
        jTxtDirecao = new javax.swing.JTextField();
        jBtnSalvarAviao = new javax.swing.JButton();
        jLblDadosAviao = new javax.swing.JLabel();
        jPnFuncoesTransformacao = new javax.swing.JPanel();
        jPnTranslandar = new javax.swing.JPanel();
        jLblTranslandarX = new javax.swing.JLabel();
        jTxtXTranslandar = new javax.swing.JTextField();
        jLblTranslandarY = new javax.swing.JLabel();
        jTxtYTranslandar = new javax.swing.JTextField();
        jBtnTranslandar = new javax.swing.JButton();
        jLblTranslandar = new javax.swing.JLabel();
        jPnEscalonar = new javax.swing.JPanel();
        jTxtXEscalonar = new javax.swing.JTextField();
        jLblEscalonarX = new javax.swing.JLabel();
        jLblEscalonarY = new javax.swing.JLabel();
        jTxtYEscalonar = new javax.swing.JTextField();
        jBtnEscalonar = new javax.swing.JButton();
        jLblEscalonar = new javax.swing.JLabel();
        jPnRotacionar = new javax.swing.JPanel();
        jLblAnguloRotacionar = new javax.swing.JLabel();
        jTxtAngularRotacionar = new javax.swing.JTextField();
        jLblCentroRotacao = new javax.swing.JLabel();
        jLblRotacionarX = new javax.swing.JLabel();
        jTxtXRotacionar = new javax.swing.JTextField();
        jTxtYRotacionar = new javax.swing.JTextField();
        jLblRotacionarY = new javax.swing.JLabel();
        jBtnRotacionar = new javax.swing.JButton();
        jLblRotacionar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Radar");
        setPreferredSize(new java.awt.Dimension(1024, 500));
        setResizable(false);

        jListRelatorio.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Avião adicionado" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListRelatorio);

        jLblRelatorio.setText("Relatório");

        javax.swing.GroupLayout jPnRadarLayout = new javax.swing.GroupLayout(jPnRadar);
        jPnRadar.setLayout(jPnRadarLayout);
        jPnRadarLayout.setHorizontalGroup(
            jPnRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPnRadarLayout.createSequentialGroup()
                .addGap(512, 512, 512)
                .addComponent(jLblRelatorio)
                .addContainerGap(515, Short.MAX_VALUE))
        );
        jPnRadarLayout.setVerticalGroup(
            jPnRadarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnRadarLayout.createSequentialGroup()
                .addGap(0, 345, Short.MAX_VALUE)
                .addComponent(jLblRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabAvioes.addTab("Radar", jPnRadar);

        jTbAvioes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Modelo", "X", "Y", "Raio", "Ângulo", "Velocidade", "Direção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbAvioes);

        jPnDadosAviao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLblX.setText("X:");

        jTxtX.setPreferredSize(new java.awt.Dimension(120, 25));

        jLblY.setText("Y:");

        jTxtY.setPreferredSize(new java.awt.Dimension(120, 25));

        jLblRaio.setText("Raio:");

        jTxtRaio.setPreferredSize(new java.awt.Dimension(120, 25));

        jLblAngulo.setText("Ângulo:");

        jTxtAngulo.setPreferredSize(new java.awt.Dimension(120, 25));

        jLblVelocidade.setText("Velocidade:");

        jTxtVelocidade.setPreferredSize(new java.awt.Dimension(120, 25));

        jLblAngulo1.setText("Direção");

        jTxtDirecao.setPreferredSize(new java.awt.Dimension(120, 25));

        jBtnSalvarAviao.setText("Salvar");
        jBtnSalvarAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalvarAviaoActionPerformed(evt);
            }
        });

        jLblDadosAviao.setText("Avião");

        javax.swing.GroupLayout jPnDadosAviaoLayout = new javax.swing.GroupLayout(jPnDadosAviao);
        jPnDadosAviao.setLayout(jPnDadosAviaoLayout);
        jPnDadosAviaoLayout.setHorizontalGroup(
            jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLblDadosAviao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnDadosAviaoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnDadosAviaoLayout.createSequentialGroup()
                        .addGroup(jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                                .addComponent(jLblVelocidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                                .addComponent(jLblRaio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                                .addComponent(jLblX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtX, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLblY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtY, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                                .addComponent(jLblAngulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                                .addComponent(jLblAngulo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtDirecao, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jBtnSalvarAviao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPnDadosAviaoLayout.setVerticalGroup(
            jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblDadosAviao)
                .addGap(21, 21, 21)
                .addGroup(jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLblY))
                    .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                        .addGroup(jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnDadosAviaoLayout.createSequentialGroup()
                                .addGroup(jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLblX)
                                    .addComponent(jTxtX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnDadosAviaoLayout.createSequentialGroup()
                                .addComponent(jTxtY, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addGroup(jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblRaio)
                            .addGroup(jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLblAngulo)
                                .addComponent(jTxtAngulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnDadosAviaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblVelocidade)
                            .addComponent(jLblAngulo1)
                            .addComponent(jTxtDirecao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSalvarAviao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnEntradaDadosLayout = new javax.swing.GroupLayout(jPnEntradaDados);
        jPnEntradaDados.setLayout(jPnEntradaDadosLayout);
        jPnEntradaDadosLayout.setHorizontalGroup(
            jPnEntradaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEntradaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnDadosAviao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(585, Short.MAX_VALUE))
        );
        jPnEntradaDadosLayout.setVerticalGroup(
            jPnEntradaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEntradaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnDadosAviao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabOperacoesAvioes.addTab("Entrada de dados", jPnEntradaDados);

        jPnTranslandar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnTranslandar.setPreferredSize(new java.awt.Dimension(230, 300));

        jLblTranslandarX.setText("X:");

        jTxtXTranslandar.setPreferredSize(new java.awt.Dimension(20, 23));

        jLblTranslandarY.setText("Y:");

        jTxtYTranslandar.setPreferredSize(new java.awt.Dimension(20, 23));

        jBtnTranslandar.setText("Translandar");

        jLblTranslandar.setText("Translandar");

        javax.swing.GroupLayout jPnTranslandarLayout = new javax.swing.GroupLayout(jPnTranslandar);
        jPnTranslandar.setLayout(jPnTranslandarLayout);
        jPnTranslandarLayout.setHorizontalGroup(
            jPnTranslandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTranslandarLayout.createSequentialGroup()
                .addGroup(jPnTranslandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnTranslandarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnTranslandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnTranslandarLayout.createSequentialGroup()
                                .addComponent(jLblTranslandarX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtXTranslandar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnTranslandarLayout.createSequentialGroup()
                                .addComponent(jLblTranslandarY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtYTranslandar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPnTranslandarLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLblTranslandar))
                    .addGroup(jPnTranslandarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnTranslandar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPnTranslandarLayout.setVerticalGroup(
            jPnTranslandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTranslandarLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLblTranslandar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnTranslandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtXTranslandar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTranslandarX, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnTranslandarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtYTranslandar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTranslandarY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnTranslandar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPnEscalonar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnEscalonar.setPreferredSize(new java.awt.Dimension(230, 300));

        jTxtXEscalonar.setPreferredSize(new java.awt.Dimension(20, 23));

        jLblEscalonarX.setText("X:");

        jLblEscalonarY.setText("Y:");

        jTxtYEscalonar.setPreferredSize(new java.awt.Dimension(20, 23));

        jBtnEscalonar.setText("Escalonar");

        jLblEscalonar.setText("Escalonar");

        javax.swing.GroupLayout jPnEscalonarLayout = new javax.swing.GroupLayout(jPnEscalonar);
        jPnEscalonar.setLayout(jPnEscalonarLayout);
        jPnEscalonarLayout.setHorizontalGroup(
            jPnEscalonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEscalonarLayout.createSequentialGroup()
                .addGroup(jPnEscalonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnEscalonarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnEscalonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblEscalonarX)
                            .addGroup(jPnEscalonarLayout.createSequentialGroup()
                                .addComponent(jLblEscalonarY)
                                .addGap(1, 1, 1)))
                        .addGroup(jPnEscalonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnEscalonarLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jTxtXEscalonar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnEscalonarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtYEscalonar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPnEscalonarLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLblEscalonar))
                    .addGroup(jPnEscalonarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jBtnEscalonar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPnEscalonarLayout.setVerticalGroup(
            jPnEscalonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnEscalonarLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLblEscalonar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnEscalonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtXEscalonar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblEscalonarX, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnEscalonarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLblEscalonarY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtYEscalonar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnEscalonar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPnRotacionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnRotacionar.setPreferredSize(new java.awt.Dimension(230, 300));

        jLblAnguloRotacionar.setText("Ângulo:");

        jTxtAngularRotacionar.setPreferredSize(new java.awt.Dimension(20, 23));

        jLblCentroRotacao.setText("Centro de Rotação");

        jLblRotacionarX.setText("X:");

        jTxtXRotacionar.setPreferredSize(new java.awt.Dimension(20, 23));

        jTxtYRotacionar.setPreferredSize(new java.awt.Dimension(20, 23));

        jLblRotacionarY.setText("Y:");

        jBtnRotacionar.setText("Rotacionar");

        jLblRotacionar.setText("Rotacionar");

        javax.swing.GroupLayout jPnRotacionarLayout = new javax.swing.GroupLayout(jPnRotacionar);
        jPnRotacionar.setLayout(jPnRotacionarLayout);
        jPnRotacionarLayout.setHorizontalGroup(
            jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnRotacionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnRotacionarLayout.createSequentialGroup()
                        .addGroup(jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPnRotacionarLayout.createSequentialGroup()
                                .addGroup(jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLblRotacionarX)
                                    .addComponent(jLblRotacionarY))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPnRotacionarLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jTxtXRotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTxtYRotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPnRotacionarLayout.createSequentialGroup()
                                    .addComponent(jLblAnguloRotacionar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtAngularRotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLblCentroRotacao))
                            .addGroup(jPnRotacionarLayout.createSequentialGroup()
                                .addComponent(jBtnRotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addContainerGap(7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnRotacionarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLblRotacionar)
                        .addGap(85, 85, 85))))
        );
        jPnRotacionarLayout.setVerticalGroup(
            jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnRotacionarLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLblRotacionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblAnguloRotacionar)
                    .addComponent(jTxtAngularRotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLblCentroRotacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtXRotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblRotacionarX, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnRotacionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtYRotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblRotacionarY, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jBtnRotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPnFuncoesTransformacaoLayout = new javax.swing.GroupLayout(jPnFuncoesTransformacao);
        jPnFuncoesTransformacao.setLayout(jPnFuncoesTransformacaoLayout);
        jPnFuncoesTransformacaoLayout.setHorizontalGroup(
            jPnFuncoesTransformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnFuncoesTransformacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnTranslandar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPnEscalonar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPnRotacionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPnFuncoesTransformacaoLayout.setVerticalGroup(
            jPnFuncoesTransformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnFuncoesTransformacaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnFuncoesTransformacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnEscalonar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(jPnTranslandar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                    .addComponent(jPnRotacionar, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPnTranslandar.getAccessibleContext().setAccessibleName("");
        jPnEscalonar.getAccessibleContext().setAccessibleName("");
        jPnRotacionar.getAccessibleContext().setAccessibleName("");

        jTabOperacoesAvioes.addTab("Funções de Transformação", jPnFuncoesTransformacao);

        javax.swing.GroupLayout jPnOperacoesAvioesLayout = new javax.swing.GroupLayout(jPnOperacoesAvioes);
        jPnOperacoesAvioes.setLayout(jPnOperacoesAvioesLayout);
        jPnOperacoesAvioesLayout.setHorizontalGroup(
            jPnOperacoesAvioesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabOperacoesAvioes)
        );
        jPnOperacoesAvioesLayout.setVerticalGroup(
            jPnOperacoesAvioesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabOperacoesAvioes)
        );

        javax.swing.GroupLayout jPnAvioesLayout = new javax.swing.GroupLayout(jPnAvioes);
        jPnAvioes.setLayout(jPnAvioesLayout);
        jPnAvioesLayout.setHorizontalGroup(
            jPnAvioesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPnOperacoesAvioes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnAvioesLayout.setVerticalGroup(
            jPnAvioesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnAvioesLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPnOperacoesAvioes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabAvioes.addTab("Aviões", jPnAvioes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabAvioes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabAvioes)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSalvarAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalvarAviaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSalvarAviaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Radar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Radar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Radar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Radar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Radar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEscalonar;
    private javax.swing.JButton jBtnRotacionar;
    private javax.swing.JButton jBtnSalvarAviao;
    private javax.swing.JButton jBtnTranslandar;
    private javax.swing.JLabel jLblAngulo;
    private javax.swing.JLabel jLblAngulo1;
    private javax.swing.JLabel jLblAnguloRotacionar;
    private javax.swing.JLabel jLblCentroRotacao;
    private javax.swing.JLabel jLblDadosAviao;
    private javax.swing.JLabel jLblEscalonar;
    private javax.swing.JLabel jLblEscalonarX;
    private javax.swing.JLabel jLblEscalonarY;
    private javax.swing.JLabel jLblRaio;
    private javax.swing.JLabel jLblRelatorio;
    private javax.swing.JLabel jLblRotacionar;
    private javax.swing.JLabel jLblRotacionarX;
    private javax.swing.JLabel jLblRotacionarY;
    private javax.swing.JLabel jLblTranslandar;
    private javax.swing.JLabel jLblTranslandarX;
    private javax.swing.JLabel jLblTranslandarY;
    private javax.swing.JLabel jLblVelocidade;
    private javax.swing.JLabel jLblX;
    private javax.swing.JLabel jLblY;
    private javax.swing.JList<String> jListRelatorio;
    private javax.swing.JPanel jPnAvioes;
    private javax.swing.JPanel jPnDadosAviao;
    private javax.swing.JPanel jPnEntradaDados;
    private javax.swing.JPanel jPnEscalonar;
    private javax.swing.JPanel jPnFuncoesTransformacao;
    private javax.swing.JPanel jPnOperacoesAvioes;
    private javax.swing.JPanel jPnRadar;
    private javax.swing.JPanel jPnRotacionar;
    private javax.swing.JPanel jPnTranslandar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabAvioes;
    private javax.swing.JTabbedPane jTabOperacoesAvioes;
    private javax.swing.JTable jTbAvioes;
    private javax.swing.JTextField jTxtAngularRotacionar;
    private javax.swing.JTextField jTxtAngulo;
    private javax.swing.JTextField jTxtDirecao;
    private javax.swing.JTextField jTxtRaio;
    private javax.swing.JTextField jTxtVelocidade;
    private javax.swing.JTextField jTxtX;
    private javax.swing.JTextField jTxtXEscalonar;
    private javax.swing.JTextField jTxtXRotacionar;
    private javax.swing.JTextField jTxtXTranslandar;
    private javax.swing.JTextField jTxtY;
    private javax.swing.JTextField jTxtYEscalonar;
    private javax.swing.JTextField jTxtYRotacionar;
    private javax.swing.JTextField jTxtYTranslandar;
    // End of variables declaration//GEN-END:variables
}
